name: GitHub Actions Demo

on:
  push: 
    branches: 
      [ "main" ]
  pull_request:
    branches: 
      [ "main" ]
  schedule: 
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build Step
    steps:
      - name: first step
        uses: actions/checkout@v3.3.0

      - name: echo out how this got kicked off
        run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."
      
      - name: list files in folder
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
        
  
