name: dump contexts
on: [workflow_dispatch]

jobs:
  dump_context:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
      - name: Dump matrix context
        run: |
          echo "::group::Matrix Context"
          echo "${{ toJson(matrix) }}"
          echo "::endgroup::"
      - name: Dump GitHub context
        run: |
          echo "::group::GitHub Context"
          echo "${{ toJson(github) }}"
          echo "::endgroup::"
      - name: Dump environment context
        run: |
          echo "::group::Environment Context"
          echo "${{ toJson(env) }}"
          echo "::endgroup::"
      - name: Dump runner context
        run: |
          echo "::group::Runner Context"
          echo "${{ toJson(runner) }}"
          echo "::endgroup::"
